#!/usr/bin/env bash

set -e

if [ ! -d "${PWD}/ha-core" ] then
git clone --branch bring-beta https://github.com/tr4nt0r/ha-core.git "${PWD}/ha-core"
fi

git -C "${PWD}/ha-core" fetch

git -C "${PWD}/ha-core" fetch switch -c bring-beta origin/bring-beta

cp -r "${PWD}/ha-core/homeassistant/components/bring" "${PWD}/custom_components"